[package]
name = "a-chat"
version = "0.1.0"
authors = ["Isan Rivkin <isan.rivkin@similarweb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.0"
async-std = "1.0.0"